@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzZGJkMDE2My1iMDQ2LTRiYzctYmY1NS1iNWMwNDdkZmMyZjEiLCJlbWFpbCI6ImNsaW50b25nZW9yZ2VAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzcxNDQyODkzLCJleHAiOjE3NzE0NDM3OTN9.AU0M-szLYJvw-XSRE3ZS8asGC30IP0wW0jt5OdiV-vM
GET http://localhost:3000/users
Authorization: Bearer {{accessToken}}
