@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMzhjYWNmMy0zYmFmLTQzMjYtOTc3My03ZTJhZGJlZGFiODMiLCJlbWFpbCI6Im1pa2V3aXp6eUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzE0NDI0NDYsImV4cCI6MTc3MTQ0MzM0Nn0.OE9lKCpV_Vnd8mmDK2e41OcL_IPfOxxZoWkQK1CNRu0

### Get My Profile
GET http://localhost:3000/customers/profile
Authorization: Bearer {{accessToken}}

