@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMzhjYWNmMy0zYmFmLTQzMjYtOTc3My03ZTJhZGJlZGFiODMiLCJlbWFpbCI6Im1pa2V3aXp6eUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzE0Mzk1NzEsImV4cCI6MTc3MTQ0MDQ3MX0.-V8tuDlBWef4TAyb9qedBIBkl3Q0mCa0Zo2YO3aK1W0
GET http://localhost:3000/users
Authorization: Bearer {{accessToken}}
