@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMWVhYTZjOC1kODVlLTRhYjktYmQyMy1hOGIyODk0NTNjNzQiLCJlbWFpbCI6ImRpdmluZWdlb3JnZUBnbWFpbC5jb20iLCJpYXQiOjE3NzEzNjUwNzEsImV4cCI6MTc3MTM2NTk3MX0.OGcmy21OPUrpoAxOWHGM3KlI5je8I7MkSd-YeToZod8

### Get My Profile
GET http://localhost:3000/customers/profile
Authorization: Bearer {{accessToken}}

