@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMzhjYWNmMy0zYmFmLTQzMjYtOTc3My03ZTJhZGJlZGFiODMiLCJlbWFpbCI6Im1pa2V3aXp6eUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzE0MzkzMDksImV4cCI6MTc3MTQ0MDIwOX0.YUBGn0SYhBiDVsh6XjPqcN8IxPyau2X11_YHCd8FWIg

### Get My Profile
GET http://localhost:3000/customers/profile
Authorization: Bearer {{accessToken}}

