@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYjQzN2Q0MC00NDFjLTRkZmEtODAyOC03YzE0ODgwYjAwOTYiLCJlbWFpbCI6ImJpb2R1bm1pa2VAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzcxNDk5NTQ2LCJleHAiOjE3NzE1MDA0NDZ9.UnTwabklfal_ltSNN1rTevbf6gWjJzMpes0GKtu0xIA
GET http://localhost:3000/users/collinsbenson@gmail.com
Authorization: Bearer {{accessToken}}