@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYjQzN2Q0MC00NDFjLTRkZmEtODAyOC03YzE0ODgwYjAwOTYiLCJlbWFpbCI6ImJpb2R1bm1pa2VAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzcxNDk2NDQ5LCJleHAiOjE3NzE0OTczNDl9.moZ74v7EuDLk9-291GlSR0uJv17PQns8AR8uAmR6LwA
GET http://localhost:3000/users
Authorization: Bearer {{accessToken}}
