@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYjQzN2Q0MC00NDFjLTRkZmEtODAyOC03YzE0ODgwYjAwOTYiLCJlbWFpbCI6ImJpb2R1bm1pa2VAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzcxNDk2MjY4LCJleHAiOjE3NzE0OTcxNjh9.eSzLKZTsYR8neKenK0wZXpI_yedvAPuHdXPtzaa4Ma0
GET http://localhost:3000/auth/login-audit
Authorization: Bearer {{accessToken}}