POST http://localhost:3000/users/register
Content-Type: application/json

{
  "email": "faithgeorge@gmail.com",
  "password": "Password123!",
  "firstName": "Faith",
  "lastName": "George",
  "phoneNumber": "080231022998"
}