POST http://localhost:3000/users/register
Content-Type: application/json

{
  "email": "clintongeorge@gmail.com",
  "password": "Password123!",
  "firstName": "Clinton",
  "lastName": "George",
  "phoneNumber": "08023102120"
}