@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYjAyZGYwMS0yODlhLTQzYzItYWRiMS1hNGFkZmY2YTcwMTQiLCJlbWFpbCI6Im1vamlzb2xhQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc3MTUwOTc5NiwiZXhwIjoxNzcxNTEwNjk2fQ.fHTClyDBwmm3iYih-kgU6YhgFvGUOfTNO0depECJzs4

GET http://localhost:3000/weather?city=Lagos
Authorization: Bearer {{accessToken}}
